"""update u user

Revision ID: 858984d93385
Revises: eda759f0f7e9
Create Date: 2024-08-24 16:27:37.205346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858984d93385'
down_revision = 'eda759f0f7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
